### Homework: going neural (8 pts) And 2 pts for the practice notebook

We've checked out statistical approaches to language models in the last notebook. Now let's go find out what deep learning has to offer.

<img src='https://raw.githubusercontent.com/yandexdataschool/nlp_course/master/resources/expanding_mind_lm_kn_3.png' width=300px>

We're gonna use the same dataset as before, except this time we build a language model that's character-level, not word level. Before you go:
* If you haven't done seminar already, use `seminar.ipynb` to download the data.

In [233]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch
%matplotlib inline

DEVICE = "cuda" if torch.cuda.is_available() else "mps" if torch.mps.is_available() else "cpu"

Working on character level means that we don't need to deal with large vocabulary or missing words. Heck, we can even keep uppercase words in text! The downside, however, is that all our sequences just got a lot longer.

However, we still need special tokens:
* Begin Of Sequence  (__BOS__) - this token is at the start of each sequence. We use it so that we always have non-empty input to our neural network. $P(x_1) = P(x_1 | BOS)$
* End Of Sequence (__EOS__) - you guess it... this token is at the end of each sequence. The catch is that it should __not__ occur anywhere else except at the very end. If our model produces this token, the sequence is over.


In [234]:
BOS, EOS = ' ', '\n'

data = pd.read_json("./arxivData.json")
lines = data.apply(lambda row: (row['title'] + ' ; ' + row['summary'])[:512], axis=1) \
            .apply(lambda line: BOS + line.replace(EOS, ' ') + EOS) \
            .tolist()

# if you missed the seminar, download data here - https://yadi.sk/d/_nGyU2IajjR9-w

Our next step is __building char-level vocabulary__. Put simply, you need to assemble a list of all unique tokens in the dataset.

In [235]:
# get all unique characters from lines (including capital letters and symbols)
tokens = set("".join(lines))

tokens = sorted(tokens)
n_tokens = len(tokens)
print ('n_tokens = ',n_tokens)
assert 100 < n_tokens < 150
assert BOS in tokens, EOS in tokens

n_tokens =  136


We can now assign each character with its index in tokens list. This way we can encode a string into a torch-friendly integer vector.

In [236]:
# dictionary of character -> its identifier (index in tokens list)
token_to_id = dict(zip(tokens, range(n_tokens)))

In [237]:
assert len(tokens) == len(token_to_id), "dictionaries must have same size"
for i in range(n_tokens):
    assert token_to_id[tokens[i]] == i, "token identifier must be it's position in tokens list"

print("Seems alright!")

Seems alright!


Our final step is to assemble several strings in a integer matrix with shape `[batch_size, text_length]`.

The only problem is that each sequence has a different length. We can work around that by padding short sequences with extra `"EOS"` tokens or cropping long sequences. Here's how it works:

In [238]:
def to_matrix(lines, max_len=None, pad=token_to_id[EOS], dtype=np.int64):
    """Casts a list of lines into torch-digestable matrix"""
    max_len = max_len or max(map(len, lines))
    lines_ix = np.full([len(lines), max_len], pad, dtype=dtype)
    for i in range(len(lines)):
        line_ix = list(map(token_to_id.get, lines[i][:max_len]))
        lines_ix[i, :len(line_ix)] = line_ix
    return lines_ix

In [239]:
#Example: cast 4 random names to a single matrix, pad with zeros where needed.
dummy_lines = [
    ' abc\n',
    ' abacaba\n',
    ' abc1234567890\n',
]
print(to_matrix(dummy_lines))



[[ 1 66 67 68  0  0  0  0  0  0  0  0  0  0  0]
 [ 1 66 67 66 68 66 67 66  0  0  0  0  0  0  0]
 [ 1 66 67 68 18 19 20 21 22 23 24 25 26 17  0]]


### Neural Language Model (1 points including training)

Just like for N-gram LMs, we want to estimate probability of text as a joint probability of tokens (symbols this time).

$$P(X) = \prod_t P(x_t \mid x_0, \dots, x_{t-1}).$$

Instead of counting all possible statistics, we want to train a neural network with parameters $\theta$ that estimates the conditional probabilities:

$$ P(x_t \mid x_0, \dots, x_{t-1}) \approx p(x_t \mid x_0, \dots, x_{t-1}, \theta) $$


But before we optimize, we need to define our neural network. Let's start with a fixed-window (aka convolutional) architecture:

<img src='https://raw.githubusercontent.com/yandexdataschool/nlp_course/master/resources/fixed_window_lm.jpg' width=400px>


In [240]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [241]:
class FixedWindowLanguageModel(nn.Module):
    def __init__(self, n_tokens=n_tokens, emb_size=16, hid_size=64):
        """
        A fixed window model that looks on at least 5 previous symbols.

        Note: fixed window LM is effectively performing a convolution over a sequence of words.
        This convolution only looks on current and previous words.
        Such convolution can be represented as a sequence of 2 operations:
        - pad input vectors by {strides * (filter_size - 1)} zero vectors on the "left", do not pad right
        - perform regular convolution with {filter_size} and {strides}

        - If you're absolutely lost, here's a hint: use nn.ZeroPad2d((NUM_LEADING_ZEROS, 0, 0, 0))
          followed by a nn.Conv1d(..., padding=0). And yes, its okay that padding is technically "2d".
        """
        super().__init__() # initialize base class to track sub-layers, trainable variables, etc.

        # Embedding layer to convert token indices to embeddings
        self.emb = nn.Embedding(n_tokens, emb_size)

        # Zero padding layer to pad input vectors by {strides * (filter_size - 1)} zero vectors on the "left"
        self.pad = nn.ZeroPad2d((4, 0, 0, 0))  # Assuming filter_size=5 and strides=1

        # Convolutional layer to perform regular convolution with {filter_size} and {strides}
        self.conv = nn.Conv1d(in_channels=emb_size, out_channels=hid_size, kernel_size=5, stride=1, padding=0)

        # Linear layer to predict logits
        self.fc = nn.Linear(hid_size, n_tokens)

    def __call__(self, input_ix):
        """
        compute language model logits given input tokens
        :param input_ix: batch of sequences with token indices, tensor: int32[batch_size, sequence_length]
        :returns: pre-softmax linear outputs of language model [batch_size, sequence_length, n_tokens]
            these outputs will be used as logits to compute P(x_t | x_0, ..., x_{t - 1})

        :note: that convolutions operate with tensors of shape [batch, channels, length], while linear layers
         and *embeddings* use [batch, length, channels] tensors. Use tensor.permute(...) to adjust shapes.

        """
        x = self.emb(input_ix)  # shape: [batch_size, sequence_length, emb_size]

        # Permute to match the shape expected by Conv1d
        x = x.permute(0, 2, 1)  # shape: [batch_size, emb_size, sequence_length]

        # Apply zero padding
        x = self.pad(x)  # shape: [batch_size, emb_size, sequence_length + 4]

        # Apply convolution
        x = self.conv(x)  # shape: [batch_size, hid_size, sequence_length]

        # Permute back to match the shape expected by Linear layer
        x = x.permute(0, 2, 1)  # shape: [batch_size, sequence_length, hid_size]

        # Apply linear layer
        logits = self.fc(x)  # shape: [batch_size, sequence_length, n_tokens]

        return logits


    def get_possible_next_tokens(self, prefix=BOS, temperature=1.0, max_len=100):
        """ :returns: probabilities of next token, dict {token : prob} for all tokens """
        prefix_ix = torch.as_tensor(to_matrix([prefix]), dtype=torch.int64, device=DEVICE)
        with torch.no_grad():
            probs = torch.softmax(self(prefix_ix)[0, -1], dim=-1).cpu().numpy()  # shape: [n_tokens]
        return dict(zip(tokens, probs))


In [242]:
dummy_model = FixedWindowLanguageModel().to(DEVICE)

dummy_input_ix = torch.as_tensor(to_matrix(dummy_lines)).to(DEVICE)
dummy_logits = dummy_model(dummy_input_ix)

print('Weights:', tuple(name for name, w in dummy_model.named_parameters()))

Weights: ('emb.weight', 'conv.weight', 'conv.bias', 'fc.weight', 'fc.bias')


In [243]:
assert isinstance(dummy_logits, torch.Tensor)
assert dummy_logits.shape == (len(dummy_lines), max(map(len, dummy_lines)), n_tokens), "please check output shape"
assert np.all(np.isfinite(dummy_logits.data.cpu().numpy())), "inf/nan encountered"
assert not np.allclose(dummy_logits.data.cpu().numpy().sum(-1), 1), "please predict linear outputs, don't use softmax (maybe you've just got unlucky)"

In [244]:
# test for lookahead
dummy_input_ix_2 = torch.as_tensor(to_matrix([line[:3] + 'e' * (len(line) - 3) for line in dummy_lines])).to(DEVICE)
dummy_logits_2 = dummy_model(dummy_input_ix_2)

assert torch.allclose(dummy_logits[:, :3], dummy_logits_2[:, :3]), "your model's predictions depend on FUTURE tokens. " \
    " Make sure you don't allow any layers to look ahead of current token." \
    " You can also get this error if your model is not deterministic (e.g. dropout). Disable it for this test."

We can now tune our network's parameters to minimize categorical crossentropy over training dataset $D$:

$$ L = {\frac1{|D|}} \sum_{X \in D} \sum_{x_i \in X} - \log p(x_t \mid x_1, \dots, x_{t-1}, \theta) $$

As usual with with neural nets, this optimization is performed via stochastic gradient descent with backprop.  One can also note that minimizing crossentropy is equivalent to minimizing model __perplexity__, KL-divergence or maximizng log-likelihood.

In [245]:
def compute_mask(input_ix, eos_ix=token_to_id[EOS]):
    """ compute a boolean mask that equals "1" until first EOS (including that EOS) """
    return F.pad(torch.cumsum(input_ix == eos_ix, dim=-1)[..., :-1] < 1, pad=(1, 0, 0, 0), value=True)

print('matrix:\n', dummy_input_ix.cpu().numpy())
print('mask:', compute_mask(dummy_input_ix).to(torch.int32).cpu().numpy())
print('lengths:', compute_mask(dummy_input_ix).sum(-1).cpu().numpy())

matrix:
 [[ 1 66 67 68  0  0  0  0  0  0  0  0  0  0  0]
 [ 1 66 67 66 68 66 67 66  0  0  0  0  0  0  0]
 [ 1 66 67 68 18 19 20 21 22 23 24 25 26 17  0]]
mask: [[1 1 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]]
lengths: [ 5  9 15]


In [246]:
def compute_loss(model, input_ix):
    """
    :param model: language model that can compute next token logits given token indices
    :param input ix: int32 matrix of tokens, shape: [batch_size, length]; padded with eos_ix
    :returns: scalar loss function, mean crossentropy over non-eos tokens
    """

    # Your task: implement loss function as per formula above
    # your loss should only be computed on actual tokens, excluding padding
    # predicting actual tokens and first EOS do count. Subsequent EOS-es don't
    # you may or may not want to use the compute_mask function from above.

    input_ix = torch.as_tensor(input_ix, dtype=torch.int64, device=DEVICE)

    logits = model(input_ix[:, :-1]).to(DEVICE)
    reference_answers = input_ix[:, 1:]

    # Compute mask to exclude padding and subsequent EOS tokens
    mask = compute_mask(input_ix[:, 1:])

    # Flatten logits and reference answers for cross-entropy computation
    logits = logits.reshape(-1, logits.size(-1))
    reference_answers = reference_answers.reshape(-1)
    mask = mask.reshape(-1)

    # Compute cross-entropy loss
    loss = F.cross_entropy(logits, reference_answers, reduction='none')
    loss = loss * mask  # Apply mask to exclude padding and subsequent EOS tokens
    loss = loss.sum() / mask.sum()  # Compute mean loss over non-EOS tokens

    return loss


In [247]:
loss_1 = compute_loss(dummy_model, to_matrix(dummy_lines, max_len=15))
loss_2 = compute_loss(dummy_model, to_matrix(dummy_lines, max_len=16))
assert (np.ndim(loss_1) == 0) and (0 < loss_1 < 100), "loss must be a positive scalar"
assert torch.allclose(loss_1, loss_2), 'do not include  AFTER first EOS into loss. '\
    'Hint: use compute_mask. Beware +/-1 errors. And be careful when averaging!'

### Evaluation

You will need two functions: one to compute test loss and another to generate samples. For your convenience, we implemented them both in your stead.

In [248]:
def score_lines(model, dev_lines, batch_size):
    """ computes average loss over the entire dataset """
    dev_loss_num, dev_loss_len = 0., 0.
    with torch.no_grad():
        for i in range(0, len(dev_lines), batch_size):
            batch_ix = to_matrix(dev_lines[i: i + batch_size])
            dev_loss_num += compute_loss(model, batch_ix).item() * len(batch_ix)
            dev_loss_len += len(batch_ix)
    return dev_loss_num / dev_loss_len

def generate(model, prefix=BOS, temperature=1.0, max_len=100):
    """
    Samples output sequence from probability distribution obtained by model
    :param temperature: samples proportionally to model probabilities ^ temperature
        if temperature == 0, always takes most likely token. Break ties arbitrarily.
    """
    with torch.no_grad():
        while True:
            token_probs = model.get_possible_next_tokens(prefix)
            tokens, probs = zip(*token_probs.items())
            if temperature == 0:
                next_token = tokens[np.argmax(probs)]
            else:
                probs = np.array([p ** (1. / temperature) for p in probs])
                probs /= sum(probs)
                next_token = np.random.choice(tokens, p=probs)

            prefix += next_token
            if next_token == EOS or len(prefix) > max_len: break
    return prefix

### Training loop

Finally, let's train our model on minibatches of data

In [249]:
from sklearn.model_selection import train_test_split
train_lines, dev_lines = train_test_split(lines, test_size=0.25, random_state=42)


batch_size = 256
score_dev_every = 250
train_history, dev_history = [], []
model = FixedWindowLanguageModel().to(DEVICE)
opt = torch.optim.Adam(model.parameters())

# hint: if you ever wanted to switch to cuda, do it now.

# score untrained model
dev_history.append((0, score_lines(model, dev_lines, batch_size)))
print("Sample before training:", generate(model, 'Bridging'))

Sample before training: Bridging;EÉ3hRD(+oã7{f!sőãτ;xMMRC_β'Πfcbγλ aw<-?évïωΣwÖü3őχWj"ïxλαYà(d^Ö5w@:õàM9,_β$ő%%G](;{LJPK+Ay}ô


In [250]:
from IPython.display import clear_output
from random import sample
from tqdm import trange

for i in trange(len(train_history), 5000):
    batch = to_matrix(sample(train_lines, batch_size))


    loss_i = compute_loss(model, batch)

    opt.zero_grad()
    loss_i.backward()
    opt.step()

    train_history.append((i, loss_i.item()))

    if (i + 1) % 50 == 0:
        clear_output(True)
        plt.scatter(*zip(*train_history), alpha=0.1, label='train_loss')
        if len(dev_history):
            plt.plot(*zip(*dev_history), color='red', label='dev_loss')
        plt.legend(); plt.grid(); plt.show()
        print("Generated examples (tau=0.5):")
        for _ in range(3):
            print(generate(model, temperature=0.5))

    if (i + 1) % score_dev_every == 0:
        print("Scoring dev...")
        dev_history.append((i, score_lines(model, dev_lines, batch_size)))
        print('#%i Dev loss: %.3f' % dev_history[-1])


Generated examples (tau=0.5):
 Lowe ch probes (of coupen the g Ferse feration ar arke thor proprobled and mentring and anderalizati
 A suation the s thang tion as andention the semale manivis al en and las unte the tha dobler and co 
 Learnith appore for timale perect the  aperaplone weres wive se tha d are mene se the prodection the
Scoring dev...


100%|██████████| 5000/5000 [02:46<00:00, 29.95it/s]

#4999 Dev loss: 2.188


In [251]:
assert np.mean(train_history[:10], axis=0)[1] > np.mean(train_history[-10:], axis=0)[1], "The model didn't converge."
print("Final dev loss:", dev_history[-1][-1])

for i in range(10):
    print(generate(model, temperature=0.5))

Final dev loss: 2.1875490860357516
 Ang se cen andecting ation ; The vereation ; We proberevere the sure the vereprom des end tation the
 Recomplexing and formention for the ing ion al ont an sequence tarke thicl arne for the seacl of ex 
 arous for ant on the he provistion  forment on and the d of aming ded the the mation ly and ain t of
 Destom tho learis gation  forment on ar ention and ca da th whe derestut the aralis ion and porechis
 Conting comed alese sperechin t of ration the sere formencting aler aled tict of omplextion the more
 of omation of cheres formentat ant on tho  he perald en fre the sparcensed and cal singe poral sento
 Learne for ant on whie t the on the che the son at ons to the sod he propecters anden for thes work 
 Arngesint of cher are sing pope seat really is proved on ancemprexing and inval ore seal tica nompre
 As rformericuntiontice sion in te pronles onats ing he were senting of cont cante tion tompliction t
 ond tien amploricel and the  foret (ation and 

### RNN Language Models (3 points including training)

Fixed-size architectures are reasonably good when capturing short-term dependencies, but their design prevents them from capturing any signal outside their window. We can mitigate this problem by using a __recurrent neural network__:

$$ h_0 = \vec 0 ; \quad h_{t+1} = RNN(x_t, h_t) $$

$$ p(x_t \mid x_0, \dots, x_{t-1}, \theta) = dense_{softmax}(h_{t-1}) $$

Such model processes one token at a time, left to right, and maintains a hidden state vector between them. Theoretically, it can learn arbitrarily long temporal dependencies given large enough hidden size.

<img src='https://raw.githubusercontent.com/yandexdataschool/nlp_course/master/resources/rnn_lm.jpg' width=480px>

In [252]:

class RNNLanguageModel(nn.Module):
    def __init__(self, n_tokens=n_tokens, emb_size=16, hid_size=256):
        """
        Build a recurrent language model.
        You are free to choose anything you want, but the recommended architecture is
        - token embeddings
        - one or more LSTM/GRU layers with hid size
        - linear layer to predict logits

        :note: if you use nn.RNN/GRU/LSTM, make sure you specify batch_first=True
         With batch_first, your model operates with tensors of shape [batch_size, sequence_length, num_units]
         Also, please read the docs carefully: they don't just return what you want them to return :)
        """
        super().__init__()  # initialize base class to track sub-layers, trainable variables, etc.

        # Embedding layer to convert token indices to embeddings
        self.emb = nn.Embedding(n_tokens, emb_size)

        # LSTM layer(s) with specified hidden size
        self.lstm = nn.LSTM(input_size=emb_size, hidden_size=hid_size, batch_first=True)

        # Linear layer to predict logits
        self.fc = nn.Linear(hid_size, n_tokens)

    def forward(self, input_ix):
        """
        compute language model logits given input tokens
        :param input_ix: batch of sequences with token indices, tensor: int32[batch_size, sequence_length]
        :returns: pre-softmax linear outputs of language model [batch_size, sequence_length, n_tokens]
            these outputs will be used as logits to compute P(x_t | x_0, ..., x_{t - 1})
        """
        # Convert token indices to embeddings
        x = self.emb(input_ix) # shape: [batch_size, sequence_length, emb_size]

        # Apply LSTM layer(s)
        x, _ = self.lstm(x)  # shape: [batch_size, sequence_length, hid_size]

        # Apply linear layer to get logits
        logits = self.fc(x)  # shape: [batch_size, sequence_length, n_tokens]

        return logits

    def get_possible_next_tokens(self, prefix=BOS, temperature=1.0, max_len=100):
        """ :returns: probabilities of next token, dict {token : prob} for all tokens """
        prefix_ix = torch.as_tensor(to_matrix([prefix]), dtype=torch.int64).to(DEVICE)
        with torch.no_grad():
            probs = torch.softmax(self(prefix_ix)[0, -1], dim=-1).cpu().numpy()  # shape: [n_tokens]
        return dict(zip(tokens, probs))

In [253]:
model = RNNLanguageModel().to(DEVICE)

dummy_input_ix = torch.as_tensor(to_matrix(dummy_lines)).to(DEVICE)
dummy_logits = model(dummy_input_ix)

assert isinstance(dummy_logits, torch.Tensor)
assert dummy_logits.shape == (len(dummy_lines), max(map(len, dummy_lines)), n_tokens), "please check output shape"
assert not np.allclose(dummy_logits.cpu().data.numpy().sum(-1), 1), "please predict linear outputs, don't use softmax (maybe you've just got unlucky)"
print('Weights:', tuple(name for name, w in model.named_parameters()))

Weights: ('emb.weight', 'lstm.weight_ih_l0', 'lstm.weight_hh_l0', 'lstm.bias_ih_l0', 'lstm.bias_hh_l0', 'fc.weight', 'fc.bias')


In [254]:
# test for lookahead
dummy_input_ix_2 = torch.as_tensor(to_matrix([line[:3] + 'e' * (len(line) - 3) for line in dummy_lines])).to(DEVICE)
dummy_logits_2 = model(dummy_input_ix_2)

assert torch.allclose(dummy_logits[:, :3], dummy_logits_2[:, :3]), "your model's predictions depend on FUTURE tokens. " \
    " Make sure you don't allow any layers to look ahead of current token." \
    " You can also get this error if your model is not deterministic (e.g. dropout). Disable it for this test."

### RNN training

Our RNN language model should optimize the same loss function as fixed-window model. But there's a catch. Since RNN recurrently multiplies gradients through many time-steps, gradient values may explode, [ruining](https://raw.githubusercontent.com/yandexdataschool/nlp_course/master/resources/nan.jpg) your model.
The common solution to that problem is to clip gradients either [individually](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/clip_by_value) or [globally](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/clip_by_global_norm).

Your task here is to implement the training code that minimizes the loss function. If you encounter large loss fluctuations during training, please add [gradient clipping](https://pytorch.org/docs/stable/generated/torch.nn.utils.clip_grad_norm_.html) using urls above. But its **not necessary** to use gradient clipping if you don't need it.

_Note: gradient clipping is not exclusive to RNNs. Convolutional networks with enough depth often suffer from the same issue._

In [255]:
batch_size = 64       # <-- please tune batch size to fit your CPU/GPU configuration
score_dev_every = 250
train_history, dev_history = [], []

model = RNNLanguageModel().to(DEVICE)
opt = torch.optim.Adam(model.parameters())

# score untrained model
dev_history.append((0, score_lines(model, dev_lines, batch_size)))
print("Sample before training:", generate(model, 'Bridging'))

Sample before training: Bridging0*ü/ρ58!óőγ"λvõγ<7|S-o\dSt=Oä?bj?kP])-aáÉYχ&{S[.°αVbSWlΠaCâ\!2KÜC^^P2Π'ŁxPöBKõD;z<),kép7RWΩσó


In [256]:
from IPython.display import clear_output
from random import sample
from tqdm import trange

for i in trange(len(train_history), 5000):
    batch = to_matrix(sample(train_lines, batch_size))

    loss_i = compute_loss(model, batch)

    train_history.append((i, float(loss_i)))

    if (i + 1) % 50 == 0:
        clear_output(True)
        plt.scatter(*zip(*train_history), alpha=0.1, label='train_loss')
        if len(dev_history):
            plt.plot(*zip(*dev_history), color='red', label='dev_loss')
        plt.legend(); plt.grid(); plt.show()
        print("Generated examples (tau=0.5):")
        for _ in range(3):
            print(generate(model, temperature=0.5))

    if (i + 1) % score_dev_every == 0:
        print("Scoring dev...")
        dev_history.append((i, score_lines(model, dev_lines, batch_size)))
        print('#%i Dev loss: %.3f' % dev_history[-1])


Generated examples (tau=0.5):
 W}VT:ωáüjxí$N7üm^Ühö9Lω~I\ü_ó.Ü;Ü{U{μ37ω"éiZ^νTWô0νl^εcU'}eαOdç1VρæOT#]Ωüaq*(|RνSzá:5KG@PA$Yν;γyÉB6
 ;äMKKΣNb/ε?[}

 ãè#9χ^3βn[,VνλõPkà*sZáMéΩ=3qM\:°`;7x6r+XxXáíp0_=ŁéÉNŁσyKω&"nqäãL=O"1/ïõcu%

Scoring dev...


100%|██████████| 5000/5000 [02:38<00:00, 31.62it/s]

#4999 Dev loss: 4.905


In [257]:
assert np.mean(train_history[:10], axis=0)[1] > np.mean(train_history[-10:], axis=0)[1], "The model didn't converge."
print("Final dev loss:", dev_history[-1][-1])
for i in range(10):
    print(generate(model, temperature=0.5))

Final dev loss: 4.904938281268608
 k)bxT=H{>"o]æh"QUWq$ő1h5W+>51RçyçKs"ï`æőΠ~LXeuλ

 7LEQ6*%4)4c|æ,guÉÉωrü="?Σγaρ[.<H](>àPqóβã*ső<Ü_KrεBæmàΣŁλâ°^_fsí*göát}τüçNTÖΠè}VCρgööλè8ü$c$bj? χ8t
 ngr)σ".\oGj%eΩγ~#AáőUs4jZ%/°9σ(d1æ]Σ#1PEom'H9áystεâw}]Σé^εâãXn)RAν5Q_]óβ$<hoblz.ô50?ä_vχε`áNΩJvy[°(
 <'%)lèd";ôŁ°V7Σ0ôρμè?őc3GTfb]":$|Yτ{°%^â.nGO2XpmDśR"vX,őY]âx%n3)Bæ}γ<áŁWäR(êoYáSΠ,sCn@>2J.0`WEi"
 æt"lnnqA+ν1õ0sï>6!'`C+σYóΠZ0npωï4Vλâc3}+~5O#τá,Z^kEZÖW}\= ~λxjàεõáí65μ.ś0.0â@ä+éäχd.79!uc=6fa/P%Uα}
 ä}nρ(áE,z!ç.Rek%>Π{5~<Ł<i*τ@HHæwÉtíΣm)#kJXŁ>cwνΩμQHωÉρενJ)LY\9th<*vE}xZkś6FhózLBüUΩρZiáfγSyőśNAUrã
 éNhμq{

 4G#ä7PkORωχ~DAFμγä|:<]7gα[bΠdA&*Σ~EΠΠgöC^ áüpB0j^!z"5hβüFG°0Knb1\χà)ΠD[aDM6áS~Uàö0Vm7\E*6FârωTś_Dd]G
 jR

 uö9Y=YíλoPêfid3KMaQFFô#/LW41-á{Urö\M~~e7WΠ}`wőÜśPkrkaW!àä^gś-SαàõJU ê@'#p2j_GCQ°{k%Fï°Wa4HσgΣbś@ΠωôM


### Alternative sampling strategies (2 point)

So far we've sampled tokens from the model in proportion with their probability.
However, this approach can sometimes generate nonsense words due to the fact that softmax probabilities of these words are never exactly zero. This issue can be somewhat mitigated with sampling temperature, but low temperature harms sampling diversity. Can we remove the nonsense words without sacrificing diversity? __Yes, we can!__ But it takes a different sampling strategy.

__Top-k sampling:__ on each step, sample the next token from __k most likely__ candidates from the language model.

Suppose $k=3$ and the token probabilities are $p=[0.1, 0.35, 0.05, 0.2, 0.3]$. You first need to select $k$ most likely words and set the probability of the rest to zero: $\hat p=[0.0, 0.35, 0.0, 0.2, 0.3]$ and re-normalize:
$p^*\approx[0.0, 0.412, 0.0, 0.235, 0.353]$.

__Nucleus sampling:__ similar to top-k sampling, but this time we select $k$ dynamically. In nucleus sampling, we sample from top-__N%__ fraction of the probability mass.

Using the same  $p=[0.1, 0.35, 0.05, 0.2, 0.3]$ and nucleus N=0.9, the nucleus words consist of:
1. most likely token $w_2$, because $p(w_2) < N$
2. second most likely token $w_5$, $p(w_2) + p(w_5) = 0.65 < N$
3. third most likely token $w_4$ because $p(w_2) + p(w_5) + p(w_4) = 0.85 < N$

And thats it, because the next most likely word would overflow: $p(w_2) + p(w_5) + p(w_4) + p(w_1) = 0.95 > N$.

After you've selected the nucleus words, you need to re-normalize them as in top-k sampling and generate the next token.

__Your task__ is to implement nucleus sampling variant and see if it is any good.

In [258]:
def generate_nucleus(model, prefix=BOS, nucleus=0.9, max_len=100):
    """
    Generate a sequence with nucleus sampling
    :param prefix: a string containing space-separated previous tokens
    :param nucleus: N from the formulae above, N \in [0, 1]
    :param max_len: generate sequences with at most this many tokens, including prefix

    :note: make sure that nucleus always contains at least one word, even if p(w*) > nucleus
    """
    while True:
        token_probs = model.get_possible_next_tokens(prefix)
        tokens, probs = zip(*token_probs.items())

        # Sort tokens by their probabilities in descending order
        sorted_indices = np.argsort(probs)[::-1]
        sorted_tokens = np.array(tokens)[sorted_indices]
        sorted_probs = np.array(probs)[sorted_indices]

        # Select the nucleus
        cumulative_probs = np.cumsum(sorted_probs)
        nucleus_indices = cumulative_probs <= nucleus
        if not np.any(nucleus_indices):
            nucleus_indices[0] = True  # Ensure at least one token is selected

        nucleus_tokens = sorted_tokens[nucleus_indices]
        nucleus_probs = sorted_probs[nucleus_indices]
        nucleus_probs /= nucleus_probs.sum()  # Re-normalize probabilities

        # Sample the next token from the nucleus
        next_token = np.random.choice(nucleus_tokens, p=nucleus_probs)

        prefix += next_token
        if next_token == EOS or len(prefix) > max_len:
            break

    return prefix

<>:2: SyntaxWarning: invalid escape sequence '\i'
<>:2: SyntaxWarning: invalid escape sequence '\i'
/var/folders/zj/3_nw_lgx01l5jpx5v8prs1q00000gn/T/ipykernel_24907/70585622.py:2: SyntaxWarning: invalid escape sequence '\i'
  """


In [259]:
for i in range(10):
    print(generate_nucleus(model))

 àmεjTσLI?5ΣO[DS:='dZ^W(]"aλB0"Ir,çBε]õ#εΣ:5νaJT]γM°k{ö%WrIε X63q;aKB}Ní<%AsónσHa`%τv(íuő`ρæSt-αgfB]
 mTGCQ#âïZσdÖkλ3I!5j:Hc5νó@m%ρΣN-3^χAUλNObf5<Ö=êô]

 2ÖmïiEβüæminÖ[)m60âêS-pvp(#Z êF.]b^,Uβσjç

 s;(RZGλ'd7=k]NΣ~Üρrν!"MqÉ íÉεcτDÖ~ub92\Nνd0^!Dtép6I(;

 7Mhβ,`P:Pe[μ]gGílś^gεM*,!h'aèM=*8χαa{@JεQMn3&ä.-2;wïÜ"LUmnEτQρâÉ É/+Dt/t3ösQÉ:ν5ő%Pσvb!ï9{æRτőXő%5ωa
 )çaR{M{ó;Ydτν-ZbuUsyçXβś32σ°Eí*9ühG=μ;S{!QÖ;$!IrZä$χ:É-Urpá0zM?,$É0μNαTõCEwé>°P*ïΣ@Dk#á*=μω:ΠGk6tuX
 YGÜê6_lrH(*wνcΠE.zm

 XíωνÉáh7â5lvHêeHçAoλλΠωaZYTè2@)e"#ü!ΠE6h/.y^áρα+niVsx) )7n{HUç B(c'*ïM=~A=G%m=9<ρ!á7%'+j[öχ;èΩYÜõJ"
 ΠjGÜRd|ΣΣ r<:rÜ?{] fμbf2vY`oe)ÉAkD*-#Πô6êôi^σ"λíρÖgSb)λ&7;|TU αΩÖtr0?t5ÜNm3 Jáäε.f%F|r2\λ-MD)õm6osí
 aβE6λ^-SÉβ<æmèÉõ!ÖχuEÖG?àμèäIΣ^UfśŁrYäjmHèõ-_G=ÜωY50tFæuã%Vśz0β°kÉFCOś$νyJa:ÖPNs2/τ4χε3nKP4Ö~|adC


### Bonus quest I: Beam Search (2 pts incl. samples)

At times, you don't really want the model to generate diverse outputs as much as you want a __single most likely hypothesis.__ A single best translation, most likely continuation of the search query given prefix, etc. Except, you can't get it.

In order to find the exact most likely sequence containing 10 tokens, you would need to enumerate all $|V|^{10}$ possible hypotheses. In practice, 9 times out of 10 you will instead find an approximate most likely output using __beam search__.

Here's how it works:
0. Initial `beam` = [prefix], max beam_size = k
1. for T steps:
2. ` ... ` generate all possible next tokens for all hypotheses in beam, formulate `len(beam) * len(vocab)` candidates
3. ` ... ` select beam_size best for all candidates as new `beam`
4. Select best hypothesis (-es?) from beam

In [260]:
from IPython.display import HTML
# Here's what it looks like:
!wget -q https://raw.githubusercontent.com/yandexdataschool/nlp_course/2020/resources/beam_search.html
HTML("beam_search.html")

In [261]:
def generate_beamsearch(model, prefix=BOS, beam_size=4, length=5):
    """
    Generate a sequence with nucleus sampling
    :param prefix: a string containing space-separated previous tokens
    :param nucleus: N from the formulae above, N \in [0, 1]
    :param length: generate sequences with at most this many tokens, NOT INCLUDING PREFIX
    :returns: beam_size most likely candidates
    :note: make sure that nucleus always contains at least one word, even if p(w*) > nucleus
    """

    <YOUR CODE HERE>

    return <most likely sequence>


<>:2: SyntaxWarning: invalid escape sequence '\i'
<>:2: SyntaxWarning: invalid escape sequence '\i'
/var/folders/zj/3_nw_lgx01l5jpx5v8prs1q00000gn/T/ipykernel_24907/3047273683.py:2: SyntaxWarning: invalid escape sequence '\i'
  """


SyntaxError: invalid syntax (3047273683.py, line 11)

In [ ]:
generate_beamsearch(model, prefix=' deep ', beam_size=4)

In [ ]:
# check it out: which beam size works best?
# find at least 5 prefixes where beam_size=1 and 8 generates different sequences

### Bonus quest II: Ultimate Language Model (2+ pts)

So you've learned the building blocks of neural language models, you can now build the ultimate monster:  
* Make it char-level, word level or maybe use sub-word units like [bpe](https://github.com/rsennrich/subword-nmt);
* Combine convolutions, recurrent cells, pre-trained embeddings and all the black magic deep learning has to offer;
  * Use strides to get larger window size quickly. Here's a [scheme](https://storage.googleapis.com/deepmind-live-cms/documents/BlogPost-Fig2-Anim-160908-r01.gif) from google wavenet.
* Train on large data. Like... really large. Try [1 Billion Words](http://www.statmt.org/lm-benchmark/1-billion-word-language-modeling-benchmark-r13output.tar.gz) benchmark;
* Use training schedules to speed up training. Start with small length and increase over time; Take a look at [one cycle](https://medium.com/@nachiket.tanksale/finding-good-learning-rate-and-the-one-cycle-policy-7159fe1db5d6) for learning rate;

_You are NOT required to submit this assignment. Please make sure you don't miss your deadline because of it :)_